### ISSUE TITLE
Object Types

### ISSUE THREAD

**Issue by wesleydmscn** [wesleydmscn-docs/typescript-roadmap#7]
These are some of the object types we can use in TypeScript:

## Interface

TypeScript allows you to specifically type an object using an interface that can be reused by multiple objects.

```ts
interface Person {
  name: string
  age: number
}

function greet(person: Person) {
  return 'Hello ' + person.name
}
```
Learn more from the following links:

[Object Types - Interfaces](https://www.typescriptlang.org/docs/handbook/2/objects.html)

## Class 

In TypeScript, a class is a blueprint for creating objects with specific properties and methods. Classes are a fundamental concept in object-oriented programming. Here is an example of a simple class in TypeScript:

```ts
class Car {
  make: string
  model: string
  year: number

  constructor(make: string, model: string, year: number) {
    this.make = make
    this.model = model
    this.year = year
  }

  drive() {
    console.log(`Driving my ${this.year} ${this.make} ${this.model}`)
  }
}
```

Learn more from the following links:

[TypeScript Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html)

## Enum

Enums is not a type-level extension of JavaScript. It allow a developer to define a set of named constants. Using enums can make it easier to document intent, or create a set of distinct cases. TypeScript provides both numeric and string-based enums.

Here is an example of a numeric enum in TypeScript:

```ts
enum Direction {
  Up = 1,
  Down,
  Left,
  Right,
}
```

Above, we have a numeric enum where `Up` is initialized with `1`. All of the following members are auto-incremented from that point on. In other words, `Direction.Up` has the value `1`, `Down ` has `2`, `Left ` has `3`, and `Right` has `4`.

If we left off the initializer for `Up`, it would have the value `0` and the rest of the members would be auto-incremented from there.

Learn more from the following links:

[TypeScript - Enums](https://www.typescriptlang.org/docs/handbook/enums.html)

## Array 

To specify the type of an array like `[1, 2, 3]`, you can use the syntax `number[]`; this syntax works for any type (e.g. `string[]` is an array of strings, and so on). You may also see this written as `Array<number>`, which means the same thing.

```ts
const numbers: number[] = [1, 2, 3]
```

Learn more from the following links:

[Arrays](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#arrays)

## Tuples

A tuple type is another sort of Array type that knows exactly how many elements it contains, and exactly which types it contains at specific positions.

```ts
type StringNumberPair = [string, number]

const pair: StringNumberPair = ['hello', 42]

const first = pair[0]
const second = pair[1]

// Error: Index out of bounds
const third = pair[2]
```

Learn more from the following links:

[Tuple Types](https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types)

## Todo

- [x] Do exercises using the object types above (Use TS-node to test your programs)

**Comment by wesleydmscn** [comment]
# Going Deeper

Here we will see deeper concepts of each type of object.

## Interface

- Property Modifiers
  - Optional Properties
  - `readonly` Properties
  - Index Signatures
- Excess Property Checks
- Extending Types
- Intersection Types
- Interfaces vs. Intersections
- Generic Object Types
  - The `Array` Type
  - The `ReadonlyArray` Type
  - Tuple Types
  - `readonly` Tuple Types

**Comment by wesleydmscn** [comment]
## Going Deeper - Classes

- [ ] [Class Members](https://www.typescriptlang.org/docs/handbook/2/classes.html#class-members)
  - Fields
  - `--strictPropertyInitialization`
  - readonly
  - Constructors
  - Super Calls
  - Methods
  - Getters / Setters
  - Index Signatures
- [ ] [Class Heritage](https://www.typescriptlang.org/docs/handbook/2/classes.html#class-heritage)
  - `implements` Clauses
  - Cautions
  - `extends` Clauses
  - Overriding Methods
  - Type-only Field Declarations
  - Initialization Order
  - Inheriting Built-in Types
- [ ] [Member Visibility](https://www.typescriptlang.org/docs/handbook/2/classes.html#member-visibility)
  - `public`
  - `protected`
  - Exposure of protected members
  - Cross-hierarchy protected access
  - `private`
  - Cross-instance private access
  - Caveats
- [ ] [Static Members](https://www.typescriptlang.org/docs/handbook/2/classes.html#static-members)
- [ ] [`static` Blocks in Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html#static-blocks-in-classes)
- [ ] [Generic Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html#generic-classes)
- [ ] [`this` at Runtime in Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-at-runtime-in-classes)
  - Arrow Functions
  - `this` parameters
- [ ] [`this` Types](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-types)
- [ ] [Parameter Properties](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties)
- [ ] [Class Expressions](https://www.typescriptlang.org/docs/handbook/2/classes.html#class-expressions)
- [ ] [Constructor Signatures](https://www.typescriptlang.org/docs/handbook/2/classes.html#constructor-signatures)
- [ ] [`abstract` Classes and Members](https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members)
- [ ] [Relationships Between Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html#relationships-between-classes)

**Comment by wesleydmscn** [comment]
## Going Deeper - Enums

- [ ] [Numeric enums](https://www.typescriptlang.org/docs/handbook/enums.html#numeric-enums)
- [ ] [String enums](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums)
- [ ] [Heterogeneous enums](https://www.typescriptlang.org/docs/handbook/enums.html#heterogeneous-enums)
- [ ] [Computed and constant members](https://www.typescriptlang.org/docs/handbook/enums.html#computed-and-constant-members)
- [ ] [Union enums and enum member types](https://www.typescriptlang.org/docs/handbook/enums.html#union-enums-and-enum-member-types)
- [ ] [Enums at runtime](https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-runtime)
- [ ] [Enums at compile time](https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-compile-time)
  - Reverse mappings
  - `const` enums
- [ ] [Ambient enums](https://www.typescriptlang.org/docs/handbook/enums.html#ambient-enums)
- [ ] [Objects vs Enums](https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums)
